import java.io.IOException;
class Excep{
public static void main(String args[]){
try{ 
int a[]={1,18,33,41,17};
System.out.println(a[7]);
}
catch(Exception e){
System.out.println(e);
}
finally{
System.out.println("Finally block executed");
}
try{
validate(18);
} 
catch(IOException e){
System.out.println(e);
}
}
public static void validate(int age) throws IOException{
if(age<18){
throw new ArithmeticException("not eligible");
}else{
System.out.println("Eligible");
}
}
}
